# Generated by Django 4.0.3 on 2022-04-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_test_paymentid'),
        ('app', '0005_auto_20220331_1836'),
    ]

    operations = [
    ]
