# Generated by Django 4.0.3 on 2022-04-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20220401_1813'),
        ('app', '0007_merge_20220401_1139'),
    ]

    operations = [
    ]
