# Generated by Django 4.0.3 on 2022-04-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20220401_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointmentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='testID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.test'),
        ),
    ]
