# Generated by Django 4.0 on 2022-04-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_payment_appointmentid_alter_payment_mode_and_more'),
        ('app', '0011_alter_payment_mode_alter_payment_testid_and_more'),
    ]

    operations = [
    ]
